apiVersion: v1
kind: Service
metadata:
  name: argo-ephemeral-api-service
  namespace: argo-ephemeral-operator-system
  labels:
    app: argo-ephemeral-api
spec:
  selector:
    app: argo-ephemeral-api
  ports:
  - name: http
    port: 8080
    targetPort: http
    protocol: TCP
  type: ClusterIP

