apiVersion: v1
kind: Service
metadata:
  name: argo-ephemeral-ui-service
  namespace: argo-ephemeral-operator-system
  labels:
    app: argo-ephemeral-ui
spec:
  selector:
    app: argo-ephemeral-ui
  ports:
  - name: http
    port: 80
    targetPort: http
    protocol: TCP
  type: ClusterIP

