apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: argo-ephemeral-operator-manager-rolebinding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: argo-ephemeral-operator-manager-role
subjects:
- kind: ServiceAccount
  name: argo-ephemeral-operator-controller-manager
  namespace: argo-ephemeral-operator-system

