apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Namespace where the operator will be deployed
namespace: argo-ephemeral-operator-system

# Resources to deploy
resources:
- manager/namespace.yaml
- rbac/service_account.yaml
- rbac/role.yaml
- rbac/role_binding.yaml
- crd/bases/ephemeral.argo.io_ephemeralapplications.yaml
- manager/deployment.yaml

# Images to use
images:
- name: argo-ephemeral-operator
  newName: argo-ephemeral-operator
  newTag: latest

